### ISSUE TITLE
manage.py migrate import issue (EveryCheese)

### ISSUE THREAD

**Issue by mgbvox** [feldroy/django-crash-starter#69] opened 2020-04-07 21:08 UTC
## What happened?

P. 98 of TwoScoops Django 3/Python 3.8 book
When running `python manage.py migrate`, encountered the following error (traceback):
`Traceback (most recent call last):
  File "manage.py", line 34, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/mgbvox/opt/anaconda3/envs/django/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/mgbvox/opt/anaconda3/envs/django/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/Users/mgbvox/opt/anaconda3/envs/django/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/mgbvox/opt/anaconda3/envs/django/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/Users/mgbvox/opt/anaconda3/envs/django/lib/python3.8/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Users/mgbvox/opt/anaconda3/envs/django/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'debug_toolbar'`

## What should've happened instead?

Should have gone off without a hitch.

## Steps to reproduce

Follow all steps in Chapter 18 up to this point.

## SOLUTION (HACKY):
run:
`conda install django-debug-toolbar`
installing the above with pip appears not to work.

Results in different error:
`Traceback (most recent call last):
  File "manage.py", line 34, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/mgbvox/opt/anaconda3/envs/django/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/mgbvox/opt/anaconda3/envs/django/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/Users/mgbvox/opt/anaconda3/envs/django/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/mgbvox/opt/anaconda3/envs/django/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/Users/mgbvox/opt/anaconda3/envs/django/lib/python3.8/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Users/mgbvox/opt/anaconda3/envs/django/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_extensions'`

condo installing django-extensions then allowed migrate to run.

Not sure what the underlying issue is here. But I do know the instructions in the book don't apply.

**Comment by luzfcb** [comment] 2020-04-07 21:31
@mgbvox Thanks for reporting the issue.

I'm going to assume that you're talking about the Django Crash Course book and not Two Scoops of Django book.

Questions:
1 - What is the Operational system your using, including the version of it?
2 - Did you ran `conda create -n everycheese python=3.8` ? (chapter 15.3)
3 - Did you ran `conda activate everycheese` ? (chapter 15.3)
4 - Did you install the python development dependencies with `pip install -r requirements/local.txt` (chapter 18.6)

**Comment by mgbvox** [comment] 2020-04-07 22:20
Hi, yes - it's the Crash Course book, not Two Scoops.

1: OS: macOS, Catalina 10.15.4
2, 3, 4 -> yes.

**Comment by sbathgate** [comment] 2020-07-22 17:33
I ran into this issue also. I realized the solution lay in 18.6 as mentioned by @luzfcb in step 4 above. I am unsure if it would possibly save some confusion with minimal impact to switch chapter 18.5 and 18.6 to avoid these issues.

**Comment by thorrak** [comment] 2020-08-15 23:10
I was having this issue as well attempting to run `manage.py migrate` as specified in section 18.5 of the Django Crash Course book. Admittedly, I'm using pip/virtualenv rather than conda. 

For me, the issue is that I installed requirements from `requirements.txt` (which in turn installed `requirements/production.txt`) by mistake in step 18.3 rather than `requirements/local.txt`. Installing the proper requirements file resolved the issue.

**Comment by luzfcb** [comment] 2020-09-22 02:59
It already fixed on this project and on the book.

**Closed by luzfcb** 2020-09-22 02:59 UTC
